import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { Icon } from '@/components/ui';
import { colors, fonts, radius, shadows, spacing } from '@/constants/theme';
import type { BettingMarket, BettingOutcome, GameLineup, TeamCode } from '@/lib/types';

const categoryOrder = [
  { type: 'match_result', label: 'Match result', icon: { ios: 'trophy.fill', android: 'emoji_events' } as const },
  { type: 'total_goals', label: 'Total goals', icon: { ios: 'number.square.fill', android: 'scoreboard' } as const },
  { type: 'player_goals', label: 'Player goals', icon: { ios: 'soccerball', android: 'sports_soccer' } as const },
  { type: 'player_assists', label: 'Player assists', icon: { ios: 'figure.soccer', android: 'assist_walker' } as const },
  { type: 'goalkeeper_saves', label: 'Goalkeeper saves', icon: { ios: 'hand.raised.fill', android: 'back_hand' } as const },
  { type: 'team_saves', label: 'Team saves', icon: { ios: 'shield.fill', android: 'shield' } as const },
  { type: 'own_goal', label: 'Own goal', icon: { ios: 'arrow.triangle.2.circlepath', android: 'sync' } as const },
];

export function MarketSections({ markets, outcomes, lineups, selected, disabled, onToggle }: { markets: BettingMarket[]; outcomes: BettingOutcome[]; lineups: GameLineup[]; selected: string[]; disabled: boolean; onToggle: (outcome: BettingOutcome) => void }) {
  return <View style={styles.sections}>{categoryOrder.map(category => { const rows = markets.filter(market => market.market_type === category.type); return rows.length ? <MarketSection key={category.type} label={category.label} icon={category.icon} markets={rows} outcomes={outcomes} lineups={lineups} selected={selected} disabled={disabled} onToggle={onToggle} /> : null; })}</View>;
}

function MarketSection({ label, icon, markets, outcomes, lineups, selected, disabled, onToggle }: { label: string; icon: Parameters<typeof Icon>[0]['name']; markets: BettingMarket[]; outcomes: BettingOutcome[]; lineups: GameLineup[]; selected: string[]; disabled: boolean; onToggle: (outcome: BettingOutcome) => void }) {
  const [open, setOpen] = useState(true);
  const split = markets.some(market => market.subject_player_id || market.subject_team);
  return <View style={styles.section}><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={() => setOpen(value => !value)} style={styles.sectionHead}><View style={styles.sectionIcon}><Icon name={icon} size={18} color={colors.gold} /></View><Text numberOfLines={1} style={styles.sectionTitle}>{label}</Text><Text style={styles.count}>{markets.length}</Text><Text style={styles.hide}>{open ? 'HIDE  ⌃' : 'SHOW  ⌄'}</Text></Pressable>{open ? <View style={styles.sectionBody}>{split ? (['A', 'B'] as TeamCode[]).map(team => <TeamMarkets key={team} team={team} markets={markets} outcomes={outcomes} lineups={lineups} selected={selected} disabled={disabled} onToggle={onToggle} />) : <MarketGroup title={markets[0]?.title || label} markets={markets} outcomes={outcomes} selected={selected} disabled={disabled} onToggle={onToggle} />}</View> : null}</View>;
}

function TeamMarkets({ team, markets, outcomes, lineups, selected, disabled, onToggle }: { team: TeamCode; markets: BettingMarket[]; outcomes: BettingOutcome[]; lineups: GameLineup[]; selected: string[]; disabled: boolean; onToggle: (outcome: BettingOutcome) => void }) {
  const totals = markets.filter(market => market.subject_team === team);
  const playerIds = [...new Set(markets.filter(market => lineups.some(row => row.team === team && row.player_id === market.subject_player_id)).map(market => market.subject_player_id).filter((id): id is string => !!id))];
  playerIds.sort((a, b) => (lineups.find(row => row.player_id === a)?.slot_index ?? 99) - (lineups.find(row => row.player_id === b)?.slot_index ?? 99));
  return <View style={[styles.team, team === 'B' && styles.teamB]}><Text style={[styles.teamTitle, team === 'B' && styles.teamTitleB]}>TEAM {team}</Text>{totals.length ? <MarketGroup title={`Team ${team} total saves`} markets={totals} outcomes={outcomes} selected={selected} disabled={disabled} onToggle={onToggle} /> : null}{playerIds.map(id => { const playerMarkets = markets.filter(market => market.subject_player_id === id); return <MarketGroup key={id} title={playerMarkets[0]?.title || 'Player'} markets={playerMarkets} outcomes={outcomes} selected={selected} disabled={disabled} onToggle={onToggle} />; })}{!totals.length && !playerIds.length ? <Text style={styles.none}>No markets for Team {team}.</Text> : null}</View>;
}

function MarketGroup({ title, markets, outcomes, selected, disabled, onToggle }: { title: string; markets: BettingMarket[]; outcomes: BettingOutcome[]; selected: string[]; disabled: boolean; onToggle: (outcome: BettingOutcome) => void }) {
  return <View style={styles.group}><Text numberOfLines={1} style={styles.groupTitle}>{title}</Text>{[...markets].sort((a, b) => Number(a.line || 0) - Number(b.line || 0)).map(market => { const rows = outcomes.filter(outcome => outcome.market_id === market.id); return <View key={market.id} style={styles.marketRow}>{market.line != null ? <View style={styles.line}><Text style={styles.lineText}>{Number(market.line).toFixed(1)}</Text></View> : null}<View style={styles.outcomes}>{rows.map(outcome => { const active = selected.includes(outcome.id); const label = market.line == null ? outcome.label : outcome.label.split(' ')[0]; return <Pressable key={outcome.id} accessibilityRole="button" accessibilityState={{ selected: active, disabled }} disabled={disabled} onPress={() => onToggle(outcome)} style={[styles.outcome, active && styles.outcomeActive, disabled && styles.disabled]}><Text numberOfLines={1} style={[styles.outcomeLabel, active && styles.activeLabel]}>{label}</Text><Text style={[styles.outcomeOdds, active && styles.activeOdds]}>{Number(outcome.offered_odds).toFixed(2)}</Text></Pressable>; })}</View></View>; })}</View>;
}

export function BetSlipDrawer({ markets, outcomes, odds, stake, potentialReturn, balanceUnits, disabled, placing, onStake, onRemove, onPlace }: { markets: BettingMarket[]; outcomes: BettingOutcome[]; odds: number; stake: string; potentialReturn: number; balanceUnits: number; disabled: boolean; placing: boolean; onStake: (value: string) => void; onRemove: (id: string) => void; onPlace: () => void }) {
  const [open, setOpen] = useState(true);
  if (!outcomes.length) return null;
  const balance = balanceUnits / 100;
  const add = (amount: number) => onStake(String(Math.min(balance, (Number(stake) || 0) + amount)));
  return <View style={styles.drawer}><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={() => setOpen(value => !value)} style={styles.drawerHead}><View style={styles.ticket}><Icon name={{ ios: 'ticket.fill', android: 'confirmation_number' }} color={colors.gold} size={16} /></View><View style={styles.drawerCopy}><Text style={styles.drawerTitle}>{outcomes.length} selection{outcomes.length === 1 ? '' : 's'}</Text><Text style={styles.drawerType}>{outcomes.length > 1 ? 'BET BUILDER' : 'SINGLE BET'}</Text></View><View><Text style={styles.oddsLabel}>ODDS</Text><Text style={styles.drawerOdds}>{odds.toFixed(2)}</Text></View><Text style={styles.drawerChevron}>{open ? '⌄' : '⌃'}</Text></Pressable>{open ? <View style={styles.drawerBody}><View style={styles.selections}>{outcomes.map(outcome => <View key={outcome.id} style={styles.selection}><View style={styles.selectionCopy}><Text numberOfLines={1} style={styles.selectionMarket}>{markets.find(market => market.id === outcome.market_id)?.title}</Text><Text numberOfLines={1} style={styles.selectionName}>{outcome.label}  <Text style={styles.selectionOdds}>{Number(outcome.offered_odds).toFixed(2)}</Text></Text></View><Pressable accessibilityLabel={`Remove ${outcome.label}`} onPress={() => onRemove(outcome.id)} style={styles.remove}><Text style={styles.removeText}>×</Text></Pressable></View>)}</View><View style={styles.stakeRow}><TextInput value={stake} onChangeText={onStake} keyboardType="decimal-pad" placeholder="Stake in coins" placeholderTextColor={colors.chalk45} style={styles.stakeInput} /><Pressable disabled={disabled || placing || Number(stake) <= 0} onPress={onPlace} style={[styles.place, (disabled || placing || Number(stake) <= 0) && styles.disabled]}><Text style={styles.placeText}>{placing ? 'Placing...' : 'Place bet'}</Text></Pressable></View><View style={styles.quick}>{[5, 10, 25].map(amount => <Pressable key={amount} onPress={() => add(amount)} style={styles.quickButton}><Text style={styles.quickText}>+{amount}</Text></Pressable>)}<Pressable onPress={() => onStake(String(balance))} style={styles.quickButton}><Text style={styles.quickText}>Max</Text></Pressable></View><View style={styles.drawerFoot}><Text style={styles.footText}>Balance {balance.toLocaleString(undefined, { maximumFractionDigits: 2 })}</Text><Text style={styles.returnText}>Potential {potentialReturn.toFixed(2)}</Text></View></View> : null}</View>;
}

const styles = StyleSheet.create({
  sections: { gap: spacing.md }, section: { overflow: 'hidden', borderWidth: 1, borderColor: colors.goldBorder, borderRadius: 21, backgroundColor: colors.ink850 }, sectionHead: { minHeight: 67, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: spacing.md }, sectionIcon: { width: 37, height: 37, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.goldBorder, borderRadius: radius.sm, backgroundColor: colors.goldSoft }, sectionTitle: { flex: 1, color: colors.chalk, fontFamily: fonts.display, fontSize: 21, textTransform: 'uppercase' }, count: { color: colors.chalk45, fontFamily: fonts.mono, fontSize: 9, borderWidth: 1, borderColor: 'rgba(245,242,232,0.07)', borderRadius: radius.pill, paddingHorizontal: 7, paddingVertical: 3 }, hide: { color: colors.chalk45, fontFamily: fonts.sansBlack, fontSize: 7, letterSpacing: 0.8 }, sectionBody: { gap: 10, borderTopWidth: 1, borderTopColor: colors.goldBorder, padding: 10 },
  team: { gap: 8, borderWidth: 1, borderColor: 'rgba(49,185,78,0.2)', borderRadius: radius.md, backgroundColor: 'rgba(49,185,78,0.025)', padding: 9 }, teamB: { borderColor: colors.goldBorder, backgroundColor: 'rgba(218,165,32,0.025)' }, teamTitle: { borderBottomWidth: 1, borderBottomColor: 'rgba(49,185,78,0.1)', color: colors.turf100, fontFamily: fonts.sansBlack, fontSize: 8, letterSpacing: 1.5, textAlign: 'center', paddingBottom: 8 }, teamTitleB: { borderBottomColor: colors.goldBorder, color: colors.gold }, none: { color: colors.chalk45, fontFamily: fonts.sans, fontSize: 10, textAlign: 'center', paddingVertical: spacing.md },
  group: { gap: 7, borderWidth: 1, borderColor: 'rgba(245,242,232,0.065)', borderRadius: 14, backgroundColor: 'rgba(0,0,0,0.15)', padding: 9 }, groupTitle: { color: colors.chalk85, fontFamily: fonts.sansBold, fontSize: 11 }, marketRow: { flexDirection: 'row', gap: 7 }, line: { minWidth: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(245,242,232,0.065)', borderRadius: 8, backgroundColor: 'rgba(245,242,232,0.025)', paddingHorizontal: 6 }, lineText: { color: colors.chalkMuted, fontFamily: fonts.mono, fontSize: 10 }, outcomes: { flex: 1, flexDirection: 'row', gap: 7 }, outcome: { flex: 1, minHeight: 48, justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(245,242,232,0.065)', borderRadius: 8, backgroundColor: 'rgba(245,242,232,0.025)', paddingHorizontal: 8 }, outcomeActive: { borderColor: 'rgba(218,165,32,0.55)', backgroundColor: 'rgba(218,165,32,0.11)' }, outcomeLabel: { color: colors.chalk45, fontFamily: fonts.sans, fontSize: 8 }, outcomeOdds: { marginTop: 2, color: colors.chalk85, fontFamily: fonts.monoBold, fontSize: 13 }, activeLabel: { color: '#B7923D' }, activeOdds: { color: colors.gold }, disabled: { opacity: 0.45 },
  drawer: { ...shadows.floating, position: 'absolute', left: 8, right: 8, bottom: 65, zIndex: 60, maxHeight: 440, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(218,165,32,0.42)', borderRadius: 22, backgroundColor: 'rgba(17,17,15,0.99)', padding: 12 }, drawerHead: { minHeight: 43, flexDirection: 'row', alignItems: 'center', gap: 9 }, ticket: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: colors.goldSoft }, drawerCopy: { flex: 1 }, drawerTitle: { color: colors.chalk, fontFamily: fonts.sansExtraBold, fontSize: 12 }, drawerType: { marginTop: 2, color: colors.chalk45, fontFamily: fonts.sansBlack, fontSize: 7, letterSpacing: 0.9 }, oddsLabel: { color: colors.chalk45, fontFamily: fonts.sansBlack, fontSize: 7 }, drawerOdds: { color: colors.gold, fontFamily: fonts.monoBold, fontSize: 14 }, drawerChevron: { color: colors.chalk45, fontFamily: fonts.sans, fontSize: 16 }, drawerBody: { borderTopWidth: 1, borderTopColor: colors.goldBorder, paddingTop: 10, gap: 8 }, selections: { maxHeight: 112, gap: 5 }, selection: { minHeight: 45, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: radius.sm, backgroundColor: 'rgba(0,0,0,0.25)', paddingHorizontal: 10 }, selectionCopy: { flex: 1 }, selectionMarket: { color: colors.chalk45, fontFamily: fonts.sans, fontSize: 7 }, selectionName: { color: colors.chalk, fontFamily: fonts.sansSemiBold, fontSize: 10 }, selectionOdds: { color: colors.gold, fontFamily: fonts.monoBold }, remove: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' }, removeText: { color: colors.chalkMuted, fontFamily: fonts.sans, fontSize: 20 }, stakeRow: { flexDirection: 'row', gap: 7 }, stakeInput: { flex: 1, minHeight: 45, borderWidth: 1, borderColor: colors.goldBorder, borderRadius: radius.sm, color: colors.chalk, fontFamily: fonts.sansMedium, fontSize: 12, paddingHorizontal: 12 }, place: { minWidth: 105, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm, backgroundColor: colors.gold, paddingHorizontal: 12 }, placeText: { color: colors.goldInk, fontFamily: fonts.sansExtraBold, fontSize: 11 }, quick: { flexDirection: 'row', gap: 5 }, quickButton: { flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.goldBorder, borderRadius: 8, backgroundColor: colors.goldSoft }, quickText: { color: colors.gold, fontFamily: fonts.sansBold, fontSize: 9 }, drawerFoot: { flexDirection: 'row', justifyContent: 'space-between' }, footText: { color: colors.chalk45, fontFamily: fonts.sans, fontSize: 8 }, returnText: { color: colors.gold, fontFamily: fonts.sansBold, fontSize: 8 },
});
