import { useEffect, useMemo, useRef, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Icon } from '@/components/ui';
import { colors, fonts, radius, shadows, spacing } from '@/constants/theme';
import type { Game } from '@/lib/types';

const MATCH_WINDOW_MS = 6 * 60 * 60 * 1000;
export function isAwaitingUpdate(game: Game, now: number) { return game.status !== 'final' && game.status !== 'live' && new Date(game.game_date).getTime() + MATCH_WINDOW_MS < now; }
export function fixtureDate(value: string, currentYear: number) { const date = new Date(value); const base = `${String(date.getDate()).padStart(2, '0')}/${String(date.getMonth() + 1).padStart(2, '0')}`; return date.getFullYear() === currentYear ? base : `${base}/${date.getFullYear()}`; }
function dateKey(value: string | Date) { const date = value instanceof Date ? value : new Date(value); return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; }
function time(value: string) { return new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }).format(new Date(value)); }

export function GameScheduleNavigator({ games, activeGames, selectedGame, now, onSelect, onOpenGame }: { games: Game[]; activeGames: Game[]; selectedGame: Game; now: number; onSelect: (id: string) => void; onOpenGame: (id: string) => void }) {
  const [calendarOpen, setCalendarOpen] = useState(false);
  const [month, setMonth] = useState(() => monthStart(new Date(selectedGame.game_date)));
  const scrollRef = useRef<ScrollView>(null);
  const index = activeGames.findIndex(game => game.id === selectedGame.id);
  const currentYear = new Date(now).getFullYear();
  useEffect(() => { scrollRef.current?.scrollTo({ x: Math.max(0, index * 112 - 85), animated: true }); }, [index]);
  const select = (game: Game) => { setMonth(monthStart(new Date(game.game_date))); onSelect(game.id); };
  return <><View style={styles.navigator}><View style={styles.navigatorHead}><View><Text style={styles.eyebrow}>FIXTURES</Text><Text style={styles.counter}>{index + 1} of {activeGames.length}</Text></View><Pressable onPress={() => { setMonth(monthStart(new Date(selectedGame.game_date))); setCalendarOpen(true); }} style={styles.calendarButton}><Icon name={{ ios: 'calendar', android: 'calendar_month' }} color={colors.gold} size={17} /><Text style={styles.calendarText}>Calendar</Text></Pressable></View><View style={styles.fixtureRow}><Pressable accessibilityLabel="Previous fixture" disabled={index <= 0} onPress={() => activeGames[index - 1] && select(activeGames[index - 1])} style={[styles.arrow, index <= 0 && styles.disabled]}><Text style={styles.arrowText}>‹</Text></Pressable><ScrollView ref={scrollRef} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.fixtureList}>{activeGames.map(game => { const active = game.id === selectedGame.id; return <Pressable key={game.id} onPress={() => select(game)} style={[styles.fixture, active && styles.fixtureActive]}><Text style={[styles.fixtureDate, active && styles.fixtureDateActive]}>{fixtureDate(game.game_date, currentYear)}</Text><Text style={styles.fixtureTime}>{game.status === 'live' ? 'Live' : time(game.game_date)}</Text></Pressable>; })}</ScrollView><Pressable accessibilityLabel="Next fixture" disabled={index >= activeGames.length - 1} onPress={() => activeGames[index + 1] && select(activeGames[index + 1])} style={[styles.arrow, index >= activeGames.length - 1 && styles.disabled]}><Text style={styles.arrowText}>›</Text></Pressable></View><Text style={styles.swipe}>Swipe the dates or use the arrows.</Text></View><GameCalendar visible={calendarOpen} month={month} games={games} activeGames={activeGames} selectedGame={selectedGame} now={now} onMonth={setMonth} onClose={() => setCalendarOpen(false)} onSelect={game => { setCalendarOpen(false); if (activeGames.some(item => item.id === game.id)) select(game); else onOpenGame(game.id); }} /></>;
}

function GameCalendar({ visible, month, games, activeGames, selectedGame, now, onMonth, onClose, onSelect }: { visible: boolean; month: Date; games: Game[]; activeGames: Game[]; selectedGame?: Game; now: number; onMonth: (date: Date) => void; onClose: () => void; onSelect: (game: Game) => void }) {
  const activeIds = useMemo(() => new Set(activeGames.map(game => game.id)), [activeGames]);
  const byDay = useMemo(() => { const map = new Map<string, Game[]>(); for (const game of games) map.set(dateKey(game.game_date), [...(map.get(dateKey(game.game_date)) || []), game]); return map; }, [games]);
  const year = month.getFullYear(); const monthIndex = month.getMonth(); const leading = (new Date(year, monthIndex, 1).getDay() + 6) % 7; const count = new Date(year, monthIndex + 1, 0).getDate();
  const cells: (Date | null)[] = [...Array.from({ length: leading }, () => null), ...Array.from({ length: count }, (_, i) => new Date(year, monthIndex, i + 1))]; while (cells.length % 7) cells.push(null);
  function preferred(day: Game[]) { return day.find(game => game.status === 'live') || day.find(game => activeIds.has(game.id)) || day.find(game => isAwaitingUpdate(game, now)) || day[0]; }
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.scrim} onPress={onClose}><Pressable style={styles.modal} onPress={() => undefined}><View style={styles.modalHead}><View><Text style={styles.eyebrow}>SCHEDULE</Text><Text style={styles.modalTitle}>GAME CALENDAR</Text></View><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><View style={styles.monthRow}><Pressable onPress={() => onMonth(new Date(year, monthIndex - 1, 1))} style={styles.monthArrow}><Text style={styles.arrowText}>‹</Text></Pressable><Text style={styles.month}>{new Intl.DateTimeFormat('en-GB', { month: 'long', year: 'numeric' }).format(month)}</Text><Pressable onPress={() => onMonth(new Date(year, monthIndex + 1, 1))} style={styles.monthArrow}><Text style={styles.arrowText}>›</Text></Pressable></View><View style={styles.week}>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(day => <Text key={day} style={styles.weekDay}>{day}</Text>)}</View><View style={styles.days}>{cells.map((date, i) => { if (!date) return <View key={`blank-${i}`} style={styles.day} />; const dayGames = byDay.get(dateKey(date)) || []; const chosen = preferred(dayGames); const selected = dateKey(date) === dateKey(selectedGame?.game_date || ''); const today = dateKey(date) === dateKey(new Date(now)); return <Pressable key={dateKey(date)} disabled={!chosen} onPress={() => chosen && onSelect(chosen)} style={[styles.day, selected ? styles.daySelected : today ? styles.dayToday : dayGames.length ? styles.dayGame : null]}><Text style={[styles.dayText, !dayGames.length && styles.dayMuted, selected && styles.daySelectedText]}>{date.getDate()}</Text>{dayGames.length ? <View style={styles.dots}>{dayGames.slice(0, 3).map(game => <View key={game.id} style={[styles.dot, game.status === 'final' ? styles.dotFinal : game.status === 'live' ? styles.dotLive : isAwaitingUpdate(game, now) ? styles.dotWaiting : null]} />)}</View> : null}</Pressable>; })}</View><View style={styles.legend}><Legend color={colors.gold} label="Scheduled" /><Legend color={colors.danger} label="Live" /><Legend color="#FDE68A" label="Awaiting update" /><Legend color={colors.turf400} label="Final" /></View></Pressable></Pressable></Modal>;
}
function Legend({ color, label }: { color: string; label: string }) { return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]} /><Text style={styles.legendText}>{label}</Text></View>; }
function monthStart(date: Date) { return new Date(date.getFullYear(), date.getMonth(), 1); }

const styles = StyleSheet.create({
  navigator: { ...shadows.card, borderWidth: 1, borderColor: colors.goldBorder, borderRadius: 19, backgroundColor: colors.ink850, padding: 11 }, navigatorHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 4, paddingBottom: 10 }, eyebrow: { color: colors.gold, fontFamily: fonts.sansBlack, fontSize: 8, letterSpacing: 1.5 }, counter: { marginTop: 2, color: colors.chalk45, fontFamily: fonts.sans, fontSize: 10 }, calendarButton: { minHeight: 43, flexDirection: 'row', alignItems: 'center', gap: 7, borderWidth: 1, borderColor: colors.goldBorder, borderRadius: radius.sm, backgroundColor: colors.goldSoft, paddingHorizontal: 11 }, calendarText: { color: colors.gold, fontFamily: fonts.sansBold, fontSize: 10 }, fixtureRow: { height: 58, flexDirection: 'row', gap: 7 }, arrow: { width: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.goldBorder, borderRadius: radius.sm, backgroundColor: 'rgba(0,0,0,0.15)' }, arrowText: { color: colors.chalk72, fontFamily: fonts.sans, fontSize: 28, lineHeight: 30 }, disabled: { opacity: 0.25 }, fixtureList: { gap: 7 }, fixture: { width: 104, justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(218,165,32,0.15)', borderRadius: radius.sm, backgroundColor: 'rgba(0,0,0,0.15)', paddingHorizontal: 11 }, fixtureActive: { borderColor: 'rgba(218,165,32,0.55)', backgroundColor: 'rgba(218,165,32,0.11)' }, fixtureDate: { color: colors.chalkMuted, fontFamily: fonts.monoBold, fontSize: 12 }, fixtureDateActive: { color: colors.gold }, fixtureTime: { marginTop: 3, color: colors.chalkMuted, fontFamily: fonts.sansSemiBold, fontSize: 8 }, swipe: { marginTop: 7, color: colors.chalk30, fontFamily: fonts.sans, fontSize: 8, textAlign: 'center' },
  scrim: { flex: 1, justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.75)', padding: spacing.md }, modal: { ...shadows.floating, borderWidth: 1, borderColor: colors.goldBorderStrong, borderRadius: radius.xl, backgroundColor: colors.ink850, padding: spacing.lg }, modalHead: { flexDirection: 'row', justifyContent: 'space-between' }, modalTitle: { color: colors.chalk, fontFamily: fonts.displayBold, fontSize: 28 }, close: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.goldBorder, borderRadius: radius.sm }, closeText: { color: colors.chalkMuted, fontSize: 23 }, monthRow: { marginTop: spacing.md, height: 54, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: colors.goldBorder, borderRadius: radius.sm, backgroundColor: 'rgba(0,0,0,0.15)', padding: 5 }, monthArrow: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.goldBorder, borderRadius: radius.sm }, month: { flex: 1, color: colors.chalk, fontFamily: fonts.sansBold, fontSize: 12, textAlign: 'center' }, week: { marginTop: spacing.md, flexDirection: 'row' }, weekDay: { flex: 1, color: colors.chalk45, fontFamily: fonts.sansBlack, fontSize: 7, textAlign: 'center' }, days: { marginTop: 5, flexDirection: 'row', flexWrap: 'wrap' }, day: { position: 'relative', width: '14.2857%', aspectRatio: 1, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.transparent, borderRadius: 10 }, dayGame: { borderColor: colors.goldBorder, backgroundColor: 'rgba(0,0,0,0.2)' }, dayToday: { borderColor: 'rgba(245,242,232,0.25)', backgroundColor: 'rgba(245,242,232,0.04)' }, daySelected: { borderColor: 'rgba(218,165,32,0.6)', backgroundColor: 'rgba(218,165,32,0.14)' }, dayText: { color: colors.chalk, fontFamily: fonts.sansBold, fontSize: 11 }, dayMuted: { color: colors.chalk30 }, daySelectedText: { color: colors.gold }, dots: { position: 'absolute', bottom: 4, flexDirection: 'row', gap: 2 }, dot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.gold }, dotFinal: { backgroundColor: colors.turf400 }, dotLive: { backgroundColor: colors.danger }, dotWaiting: { backgroundColor: '#FDE68A' }, legend: { marginTop: spacing.md, flexDirection: 'row', flexWrap: 'wrap', gap: 10, borderTopWidth: 1, borderTopColor: colors.goldBorder, paddingTop: spacing.md }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 }, legendDot: { width: 6, height: 6, borderRadius: 3 }, legendText: { color: colors.chalkMuted, fontFamily: fonts.sansSemiBold, fontSize: 8 },
});
