import { useState, type ReactNode } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import Constants from 'expo-constants';

import { AdminBack } from '@/components/AdminChrome';
import { LeagueHeader } from '@/components/LeagueChrome';
import { Button, Card, Icon, Loading, Message, Screen } from '@/components/ui';
import { colors, fonts, radius, spacing } from '@/constants/theme';
import { useScopedLeague } from '@/hooks/useScopedLeague';
import { friendlyMobileError } from '@/lib/api';
import { isInternalLoginEmail } from '@/lib/auth';
import { useAuth } from '@/providers/AuthProvider';

export default function SettingsScreen() {
  const router = useRouter();
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const { user, signOut } = useAuth();
  const { league, membership, loading, switching } = useScopedLeague(slug);
  const [message, setMessage] = useState<string | null>(null);
  if (loading || switching || !league) return <Loading label="Loading settings..." />;
  async function logout() { try { await signOut(); router.replace('/account'); } catch (error) { setMessage(friendlyMobileError(error, 'You could not be signed out.')); } }
  const admin = membership?.role === 'owner' || membership?.role === 'admin';
  const recovery = user?.new_email ? `Verification pending for ${user.new_email}` : user?.email && !isInternalLoginEmail(user.email) ? `Verified recovery email: ${user.email}` : 'No verified recovery email yet.';
  return <Screen header={<LeagueHeader league={league} />} compact><AdminBack label="Profile" onPress={() => router.back()} /><View style={styles.intro}><Text style={styles.eyebrow}>YOUR ACCOUNT</Text><Text style={styles.title}>SETTINGS</Text><Text style={styles.body}>League access, preferences, security, help and legal information.</Text></View>{message ? <Message tone="error">{message}</Message> : null}<SettingsCard title="League" icon={{ ios: 'shield.fill', android: 'shield' }}><SettingsLink label="Players and statistics" detail="Browse the active league roster" icon={{ ios: 'person.2.fill', android: 'group' }} onPress={() => router.push(`/l/${league.slug}/players`)} /><SettingsLink label="Switch or add league" detail="Open your league list" icon={{ ios: 'arrow.left.arrow.right', android: 'swap_horiz' }} onPress={() => router.push('/leagues')} />{admin ? <SettingsLink label="League Admin" detail="Games, roster, seasons and members" icon={{ ios: 'slider.horizontal.3', android: 'tune' }} onPress={() => router.push(`/l/${league.slug}/admin`)} /> : null}</SettingsCard><SettingsCard title="Preferences" icon={{ ios: 'gearshape.fill', android: 'settings' }}><SettingsLink label="Notifications" detail="Device alerts and league reminders" icon={{ ios: 'bell.fill', android: 'notifications' }} onPress={() => router.push(`/l/${league.slug}/notifications`)} /><SettingsLink label="Account security" detail={recovery} icon={{ ios: 'lock.shield.fill', android: 'admin_panel_settings' }} onPress={() => router.push(`/l/${league.slug}/account-security`)} /></SettingsCard><SettingsCard title="Help & legal" icon={{ ios: 'questionmark.circle.fill', android: 'help' }}><SettingsLink label="Support" detail="Get help or contact us" icon={{ ios: 'lifepreserver.fill', android: 'support_agent' }} onPress={() => router.push('/legal/support')} /><SettingsLink label="Privacy Policy" icon={{ ios: 'hand.raised.fill', android: 'privacy_tip' }} onPress={() => router.push('/legal/privacy')} /><SettingsLink label="Terms of Use" icon={{ ios: 'doc.text.fill', android: 'description' }} onPress={() => router.push('/legal/terms')} /><SettingsLink label="Delete account" detail="Permanently remove your account" icon={{ ios: 'trash.fill', android: 'delete' }} danger onPress={() => router.push(`/l/${league.slug}/account-security`)} /></SettingsCard><Button variant="secondary" icon={{ ios: 'rectangle.portrait.and.arrow.right', android: 'logout' }} onPress={logout}>Sign out</Button><Text style={styles.version}>THURSDAY LEAGUE · VERSION {Constants.expoConfig?.version || '1.0.0'}</Text></Screen>;
}
function SettingsCard({ title, icon, children }: { title: string; icon: Parameters<typeof Icon>[0]['name']; children: ReactNode }) { return <Card style={styles.card}><View style={styles.cardHeader}><View style={styles.cardIcon}><Icon name={icon} size={19} color={colors.gold} /></View><Text style={styles.cardTitle}>{title}</Text></View><View style={styles.rows}>{children}</View></Card>; }
function SettingsLink({ label, detail, icon, danger = false, onPress }: { label: string; detail?: string; icon: Parameters<typeof Icon>[0]['name']; danger?: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.linkRow, pressed && styles.pressed]}><View style={[styles.linkIcon, danger && styles.linkIconDanger]}><Icon name={icon} size={18} color={danger ? colors.danger : colors.chalkMuted} /></View><View style={styles.linkCopy}><Text style={[styles.linkLabel, danger && styles.linkDanger]}>{label}</Text>{detail ? <Text numberOfLines={2} style={styles.linkDetail}>{detail}</Text> : null}</View><Icon name={{ ios: 'chevron.right', android: 'chevron_right' }} size={17} color={colors.chalk30} /></Pressable>; }
const styles = StyleSheet.create({ intro: { gap: 3 }, eyebrow: { color: '#B18A37', fontFamily: fonts.sansBlack, fontSize: 8, letterSpacing: 1.6 }, title: { color: colors.chalk, fontFamily: fonts.displayBold, fontSize: 42 }, body: { color: colors.chalk45, fontFamily: fonts.sans, fontSize: 11, lineHeight: 17 }, card: { padding: 0, gap: 0, overflow: 'hidden' }, cardHeader: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: 1, borderBottomColor: colors.goldBorder, paddingHorizontal: spacing.md }, cardIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm, backgroundColor: colors.goldSoft }, cardTitle: { color: colors.chalk, fontFamily: fonts.display, fontSize: 23, textTransform: 'uppercase' }, rows: { paddingHorizontal: spacing.sm }, linkRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.goldBorder, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm }, linkIcon: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm, backgroundColor: 'rgba(245,242,232,0.035)' }, linkIconDanger: { backgroundColor: colors.dangerSoft }, linkCopy: { flex: 1 }, linkLabel: { color: colors.chalk85, fontFamily: fonts.sansBold, fontSize: 12 }, linkDanger: { color: colors.danger }, linkDetail: { marginTop: 3, color: colors.chalkMuted, fontFamily: fonts.sans, fontSize: 9, lineHeight: 14 }, pressed: { opacity: 0.68 }, version: { color: colors.chalk30, fontFamily: fonts.sansBlack, fontSize: 8, letterSpacing: 1.2, textAlign: 'center' } });
